import { Link } from 'react-router-dom'
import { lifestyles } from '../data/discovery'
import { slugify } from '../data/propertyDiscovery'
import { editorialImages, representedPlaces } from '../data/editorialPages'
import Photo from '../components/ui/Photo'
import Reveal from '../components/ui/Reveal'
import '../styles/editorial.css'

const principles = [
  ['Place', 'A home belongs to its surroundings as much as its floor plan.', 'The neighbourhood, the outlook and the everyday routes around it are part of the residence.'],
  ['Space', 'Square footage matters. How that space feels matters too.', 'Light, circulation and room to pause give the numbers a more human meaning.'],
  ['Life', 'The right residence depends on the life happening inside it.', 'A quiet morning, a shared table, a place to work. Different lives ask different things of home.'],
]
export default function About() {
  return <div className="editorial-page about-page">
    <header className="about-opening container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link to="/">← Home</Link><span>/</span><span aria-current="page">About</span></nav><p className="eyebrow">04 / About</p><div className="about-opening-grid"><div><h1>Property,<br />considered<br />differently.</h1><p>Havenza begins with a simple idea: finding a home should start with how you want to live.</p></div><figure><Photo image={editorialImages.aboutOpening} eager /><figcaption className="eyebrow">A closer look / Havenza</figcaption></figure></div></header>
    <section className="about-idea container editorial-split" aria-labelledby="idea-heading"><div><p className="eyebrow">01 / A point of view</p><h2 id="idea-heading">The idea.</h2></div><div><p className="editorial-lead">A price, a bedroom count and a floor area describe a property. They only begin to describe a home.</p><p>Havenza brings those practical details together with place, space and the rhythm of everyday life. It is an invitation to look a little closer at how a residence might fit.</p><p className="about-idea-signature">Place. Space. Life.</p></div></section>
    <section className="about-principles container" aria-labelledby="principles-heading"><h2 id="principles-heading" className="eyebrow">02 / Three ways of looking</h2><ol>{principles.map(([title, statement, copy], index) => <li key={title}><span className="about-principle-number">0{index + 1}</span><h3>{title}</h3><div><p>{statement}</p><p>{copy}</p></div></li>)}</ol></section>
    <section className="about-atlas" aria-labelledby="about-atlas-heading"><div className="container editorial-split"><div><p className="eyebrow">03 / An index, not just an inventory</p><h2 id="about-atlas-heading">The<br />Property Atlas.</h2><p>Explore residences through four connected perspectives. Start with a place or a feeling, then bring the practical details into focus.</p><Link className="line-link" to="/properties">Explore the Atlas <span aria-hidden="true">→</span></Link></div><dl className="about-atlas-diagram" aria-label="Four perspectives in the Property Atlas">{[['Place', 'Neighbourhoods and states'], ['Purpose', 'Ownership or renting'], ['Space', 'Bedrooms, floor area and price'], ['Atmosphere', 'A way of living']].map(([term, description], index) => <div key={term}><dt><span>0{index + 1}</span>{term}</dt><dd>{description}</dd></div>)}</dl></div></section>
    <section className="about-life container editorial-split" aria-labelledby="about-life-heading"><div><p className="eyebrow">04 / Life index</p><h2 id="about-life-heading">More than<br />a postcode.</h2><p>Some lives reach toward the city. Others ask for a little more quiet, room or greenery. The Life Index offers a starting point for each.</p></div><div className="about-life-list">{lifestyles.map(lifestyle => <Link key={lifestyle.id} to={`/properties?atmosphere=${lifestyle.id}`}><h3>{lifestyle.title}</h3><p>{lifestyle.description}</p><span aria-hidden="true">↗</span></Link>)}<Link className="line-link" to="/properties">Find your index <span aria-hidden="true">→</span></Link></div></section>
    <section className="about-malaysia container" aria-labelledby="malaysia-heading"><div className="editorial-split"><div><p className="eyebrow">05 / The collection</p><h2 id="malaysia-heading">Different rhythms.<br />Across Malaysia.</h2></div><div><p className="editorial-lead">From vertical city living to homes with more room around them, this fictional collection explores different residential rhythms across Malaysia.</p><nav aria-label="Represented states">{representedPlaces.map(place => <Link key={place.state} to={`/properties?state=${slugify(place.state)}`}>{place.state} <span>{place.residences.length} {place.residences.length === 1 ? 'residence' : 'residences'} ↗</span></Link>)}</nav></div></div><div className="about-malaysia-images">{editorialImages.malaysia.map((image, index) => <Reveal key={image.src} className={`about-malaysia-frame frame-${index}`}><Photo image={image} /></Reveal>)}</div></section>
    <section className="about-transparency" aria-labelledby="transparency-heading"><div className="container editorial-split"><div><p className="eyebrow">06 / The portfolio project</p><h2 id="transparency-heading">Behind<br />Havenza.</h2></div><div><p className="editorial-lead">Havenza is a fictional real-estate concept created as a web design and development portfolio demonstration.</p><p>The residences are fictional, photography is illustrative, and enquiries are demonstrations. No properties are actually offered for sale or rent through Havenza.</p><Link className="line-link" to="/contact#developer-enquiry">About the website project <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="editorial-photo-closing" aria-labelledby="about-closing-heading"><Photo image={editorialImages.aboutClosing} /><div className="editorial-photo-shade" /><div className="container"><p className="eyebrow">A different perspective on home</p><h2 id="about-closing-heading">Find the place<br />that fits.</h2><Link className="line-link" to="/properties">Explore the Property Atlas <span aria-hidden="true">→</span></Link><p className="editorial-photo-disclosure">Fictional residences. Photography is illustrative.</p></div></section>
  </div>
}
