import Photo from '../ui/Photo'
import { ResidenceInformation } from './CollectionParts'
import usePropertyRail from '../../hooks/usePropertyRail'
import { padIndex } from '../../data/discovery'

export default function RentalSequence({ collection }) {
  const { railRef, active, browse, handlers } = usePropertyRail(collection.selected.length)
  return <section className="rental-sequence" aria-labelledby="rental-sequence-heading"><div className="container collection-sequence-heading"><div className="collection-section-heading"><p className="eyebrow">01 / The rental collection</p><h2 id="rental-sequence-heading">Places for now.</h2></div><p>Different spaces.<br />Different chapters.</p></div><div className="rental-track" id="rental-residences" ref={railRef} tabIndex={0} role="region" aria-label="Rental residences" aria-describedby="rental-instructions" {...handlers}>{collection.selected.map((property, index) => <article key={property.id} className="rental-frame" data-residence={property.id}><div className="rental-frame-image"><Photo image={property.image} /></div><ResidenceInformation property={property} index={index} path={collection.path} /></article>)}</div><div className="container rental-toolbar"><p role="status" aria-live="polite" aria-atomic="true"><span className="sr-only">Residence </span>{padIndex(active + 1)} <span>/ {padIndex(collection.selected.length)}</span></p><span className="rental-gesture">Swipe / scroll to explore →</span><div><button type="button" aria-label="Previous rental" aria-controls="rental-residences" disabled={active === 0} onClick={() => browse(-1)}>←</button><button type="button" aria-label="Next rental" aria-controls="rental-residences" disabled={active === collection.selected.length - 1} onClick={() => browse(1)}>→</button></div></div><p className="sr-only" id="rental-instructions">Swipe, scroll horizontally, drag with a mouse or use the previous and next buttons. With this gallery focused, use Left and Right arrow keys, Home and End. Tab reaches each residence link and Save button.</p></section>
}
